"""Initial

Revision ID: 4fd53c6e9ba4
Revises: 
Create Date: 2026-10-02 17:48:28.418590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd53c6e9ba4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('model_status', sa.Enum('not_available', 'training', 'ready', 'validation_required', name='model_status_enum', native_enum=False), nullable=False),
    sa.Column('reference_image_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('code', name=op.f('uq_products_code'))
    )
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('client_type', sa.Enum('web', 'mobile', name='client_type_enum', native_enum=False), nullable=False),
    sa.Column('decision', sa.Enum('PASS', 'FAIL', 'REVIEW', name='decision_enum', native_enum=False), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('heatmap_url', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inspections_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    op.create_table('product_reference_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_reference_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_reference_images'))
    )
    op.create_table('product_threshold_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('old_threshold', sa.Float(), nullable=False),
    sa.Column('new_threshold', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_threshold_history_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_threshold_history'))
    )
    op.create_table('defects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='severity_enum', native_enum=False), nullable=False),
    sa.Column('region_x', sa.Float(), nullable=True),
    sa.Column('region_y', sa.Float(), nullable=True),
    sa.Column('region_width', sa.Float(), nullable=True),
    sa.Column('region_height', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_defects_inspection_id_inspections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defects'))
    )
    op.create_table('inspection_runtime',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('engine_name', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_inspection_runtime_inspection_id_inspections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_runtime'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspection_runtime')
    op.drop_table('defects')
    op.drop_table('product_threshold_history')
    op.drop_table('product_reference_images')
    op.drop_table('inspections')
    op.drop_table('products')
    # ### end Alembic commands ###
